version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: rustyassets
      POSTGRES_USER: rustyassets
      POSTGRES_PASSWORD: rustyassets
    ports:
      - "5432:5432"
    volumes:
      - rustyassets_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rustyassets -d rustyassets"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  rustyassets_postgres_data: