# Tarpaulin Configuration for RustyAssets
# https://github.com/xd009642/tarpaulin

[run]
# Run tests with full feature set and workspace
all-features = true
workspace = true
timeout = "120s"
follow-symlinks = true

# Test execution options
skip-clean = false
frozen = false
locked = false

[report]
# Output formats for different use cases
out = ["Html", "Xml", "Json"]

# Coverage calculation options
count = false
branch = false
forward = false
# Disabled external services by default
ciserver = "github"

[coverage]
# Files to exclude from coverage calculation
exclude-files = [
    # Database migrations are infrastructure, not business logic
    "*/migrations/*",
    
    # Build artifacts and dependencies
    "*/target/*",
    "*/deps/*",
    
    # Test files themselves don't need coverage
    "*/tests/*",
    
    # Integration test utilities
    "*/test_utils.rs",
    "*/test_helpers.rs",
    
    # Generated code and build scripts
    "*/build.rs",
    "*/proto/*",
    "*/.cargo/*"
]

# Note: Function exclusions can be added via command line if needed
# Common exclusions: main, test*, *::fmt::Debug*, *::default::Default*

# Note: Coverage thresholds are enforced in CI/CD, not here
# Target thresholds:
# - assets-core: 80% (core business logic)
# - assets-cli: 70% (CLI commands)
# - assets-demo: 60% (demo data)

# These advanced sections are not supported in all tarpaulin versions
# so we keep the config minimal and use command-line options instead