[package]
name = "assets-demo"
version = "0.1.0"
edition.workspace = true

[dependencies]
assets-core = { path = "../assets-core" }
tokio = { version = "1.0", features = ["full"] }
log = "0.4"
anyhow = "1.0"
chrono = "0.4.41"
rust_decimal = "1.37.2"

[lints]
workspace = true
