use anyhow::Result;
use ratatui::{
    layout::{Constraint, Direction, Layout, Rect},
    style::{Color, Modifier, Style},
    text::{Line, Span},
    widgets::{Block, Borders, Clear, List, ListItem, ListState, Paragraph, Wrap},
    Frame,
};

use crate::component::{Action, Component, CreateAccountData};
use crate::database::AppDatabase;
use assets_core::{AccountSubtype, AccountType};

/// Account creation form component
pub struct AccountFormComponent {
    db: Option<AppDatabase>,
    is_visible: bool,
    current_step: FormStep,
    form_data: AccountFormData,
    input_buffer: String,
    error_message: Option<String>,
    account_types: Vec<AccountType>,
    account_type_selection: ListState,
    subtypes: Vec<AccountSubtype>,
    subtype_selection: ListState,
}

#[derive(Debug, Clone, PartialEq)]
enum FormStep {
    AccountType,
    AccountSubtype,
    AccountName,
    // TODO: Remove account code entirely - it should be auto-generated by the system
    // AccountCode step removed - code is now auto-generated
    Confirmation,
}

#[derive(Debug, Clone, Default)]
struct AccountFormData {
    account_type: Option<AccountType>,
    account_subtype: Option<AccountSubtype>,
    name: String,
    code: String,
    currency: String,
}

impl AccountFormComponent {    pub fn new() -> Self {
        let account_types = vec![
            AccountType::Asset,
            AccountType::Liability,
            AccountType::Equity,
            AccountType::Income,
            AccountType::Expense,
        ];
        
        let mut account_type_selection = ListState::default();
        account_type_selection.select(Some(0)); // Select first item by default
        
        Self {
            db: None,
            is_visible: false,
            current_step: FormStep::AccountType,
            form_data: AccountFormData {
                currency: "EUR".to_string(),
                ..Default::default()
            },
            input_buffer: String::new(),
            error_message: None,
            account_types,
            account_type_selection,
            subtypes: Vec::new(),
            subtype_selection: ListState::default(),
        }
    }

    pub fn init_with_db(&mut self, db: AppDatabase) -> Result<()> {
        self.db = Some(db);
        Ok(())
    }    pub fn show(&mut self) {
        self.is_visible = true;
        self.current_step = FormStep::AccountType;
        self.form_data = AccountFormData {
            currency: "EUR".to_string(),
            ..Default::default()
        };
        self.input_buffer.clear();
        self.error_message = None;
        self.account_type_selection.select(Some(0)); // Reset to first item
        self.subtypes.clear();
    }

    pub fn hide(&mut self) {
        self.is_visible = false;
        self.input_buffer.clear();
        self.error_message = None;
    }

    pub fn is_visible(&self) -> bool {
        self.is_visible
    }    fn next_step(&mut self) {
        match self.current_step {
            FormStep::AccountType => {
                if let Some(selected) = self.account_type_selection.selected() {
                    if let Some(account_type) = self.account_types.get(selected) {
                        self.form_data.account_type = Some(account_type.clone());
                        self.populate_subtypes();
                        self.current_step = FormStep::AccountSubtype;
                        self.subtype_selection.select(Some(0));
                    }
                }
            }
            FormStep::AccountSubtype => {
                if self.form_data.account_subtype.is_some() {
                    self.current_step = FormStep::AccountName;
                    self.input_buffer.clear();
                }
            }            FormStep::AccountName => {
                if !self.input_buffer.trim().is_empty() {
                    self.form_data.name = self.input_buffer.trim().to_string();
                    // Auto-generate account code based on type and name
                    self.generate_account_code();
                    self.current_step = FormStep::Confirmation;
                    self.input_buffer.clear();
                }
            }
            FormStep::Confirmation => {
                // Will be handled in handle_events
            }
        }
    }    fn previous_step(&mut self) {
        match self.current_step {
            FormStep::AccountType => {}
            FormStep::AccountSubtype => {
                self.current_step = FormStep::AccountType;
                self.subtypes.clear();
                // Keep account type selection as is for user convenience
            }
            FormStep::AccountName => {
                self.current_step = FormStep::AccountSubtype;
                self.input_buffer.clear();
            }
            FormStep::Confirmation => {
                self.current_step = FormStep::AccountName;
                self.input_buffer = self.form_data.name.clone();
            }
        }
    }

    fn populate_subtypes(&mut self) {
        if let Some(account_type) = &self.form_data.account_type {
            self.subtypes = match account_type {
                AccountType::Asset => vec![
                    AccountSubtype::Cash,
                    AccountSubtype::Checking,
                    AccountSubtype::Savings,
                    AccountSubtype::InvestmentAccount,
                    AccountSubtype::Stocks,
                    AccountSubtype::Etf,
                    AccountSubtype::Bonds,
                    AccountSubtype::MutualFund,
                    AccountSubtype::Crypto,
                    AccountSubtype::RealEstate,
                    AccountSubtype::Equipment,
                    AccountSubtype::OtherAsset,
                ],
                AccountType::Liability => vec![
                    AccountSubtype::CreditCard,
                    AccountSubtype::Loan,
                    AccountSubtype::Mortgage,
                    AccountSubtype::OtherLiability,
                ],
                AccountType::Equity => vec![
                    AccountSubtype::OpeningBalance,
                    AccountSubtype::RetainedEarnings,
                    AccountSubtype::OwnerEquity,
                ],
                AccountType::Income => vec![
                    AccountSubtype::Salary,
                    AccountSubtype::Bonus,
                    AccountSubtype::Dividend,
                    AccountSubtype::Interest,
                    AccountSubtype::Investment,
                    AccountSubtype::Rental,
                    AccountSubtype::CapitalGains,
                    AccountSubtype::OtherIncome,
                ],
                AccountType::Expense => vec![
                    AccountSubtype::Food,
                    AccountSubtype::Housing,
                    AccountSubtype::Transportation,
                    AccountSubtype::Communication,
                    AccountSubtype::Entertainment,
                    AccountSubtype::Personal,
                    AccountSubtype::Utilities,
                    AccountSubtype::Healthcare,
                    AccountSubtype::Taxes,
                    AccountSubtype::Fees,
                    AccountSubtype::OtherExpense,
                ],
            };        }
    }

    fn generate_account_code(&mut self) {
        // TODO: Remove this method entirely when account codes are auto-generated by the system
        // Auto-generate a simple account code based on account type and name
        if let Some(account_type) = &self.form_data.account_type {
            let base_code = match account_type {
                AccountType::Asset => "1",
                AccountType::Liability => "2", 
                AccountType::Equity => "3",
                AccountType::Income => "4",
                AccountType::Expense => "5",
            };
            
            // Create a simple code from first letters of name words + base
            let name_part: String = self.form_data.name
                .split_whitespace()
                .take(3)
                .map(|word| word.chars().next().unwrap_or('X').to_uppercase().to_string())
                .collect::<Vec<_>>()
                .join("");
            
            self.form_data.code = format!("{}{}", base_code, name_part);
        }
    }

    fn get_account_type_display_name(account_type: &AccountType) -> &'static str {
        match account_type {
            AccountType::Asset => "Asset (Cash, Investments, Property)",
            AccountType::Liability => "Liability (Credit Cards, Loans)",
            AccountType::Equity => "Equity (Owner's Equity, Retained Earnings)",
            AccountType::Income => "Income (Salary, Dividends, Interest)",
            AccountType::Expense => "Expense (Food, Utilities, Transportation)",
        }
    }

    fn get_subtype_display_name(subtype: &AccountSubtype) -> &'static str {
        match subtype {
            AccountSubtype::Cash => "Cash",
            AccountSubtype::Checking => "Checking Account",
            AccountSubtype::Savings => "Savings Account",
            AccountSubtype::InvestmentAccount => "Investment Account",
            AccountSubtype::Stocks => "Individual Stocks",
            AccountSubtype::Etf => "ETFs",
            AccountSubtype::Bonds => "Bonds",
            AccountSubtype::MutualFund => "Mutual Funds",
            AccountSubtype::Crypto => "Cryptocurrency",
            AccountSubtype::RealEstate => "Real Estate",
            AccountSubtype::Equipment => "Equipment",
            AccountSubtype::OtherAsset => "Other Asset",
            AccountSubtype::CreditCard => "Credit Card",
            AccountSubtype::Loan => "Personal Loan",
            AccountSubtype::Mortgage => "Mortgage",
            AccountSubtype::OtherLiability => "Other Liability",
            AccountSubtype::OpeningBalance => "Opening Balance Equity",
            AccountSubtype::RetainedEarnings => "Retained Earnings",
            AccountSubtype::OwnerEquity => "Owner's Equity",
            AccountSubtype::Salary => "Salary",
            AccountSubtype::Bonus => "Bonus",
            AccountSubtype::Dividend => "Dividends",
            AccountSubtype::Interest => "Interest Income",
            AccountSubtype::Investment => "Investment Income",
            AccountSubtype::Rental => "Rental Income",
            AccountSubtype::CapitalGains => "Capital Gains",
            AccountSubtype::OtherIncome => "Other Income",
            AccountSubtype::Food => "Food & Dining",
            AccountSubtype::Housing => "Housing",
            AccountSubtype::Transportation => "Transportation",
            AccountSubtype::Communication => "Phone & Internet",
            AccountSubtype::Entertainment => "Entertainment",
            AccountSubtype::Personal => "Personal Care",
            AccountSubtype::Utilities => "Utilities",
            AccountSubtype::Healthcare => "Healthcare",
            AccountSubtype::Taxes => "Taxes",
            AccountSubtype::Fees => "Bank Fees",
            AccountSubtype::OtherExpense => "Other Expense",
        }
    }
}

impl Component for AccountFormComponent {
    fn init(&mut self) -> Result<()> {
        Ok(())
    }

    fn handle_events(&mut self, event: crossterm::event::Event) -> Result<Option<Action>> {
        if !self.is_visible {
            return Ok(None);
        }

        if let crossterm::event::Event::Key(key) = event {
            if key.kind == crossterm::event::KeyEventKind::Press {
                match key.code {
                    crossterm::event::KeyCode::Esc => {
                        self.hide();
                        return Ok(None);
                    }                    crossterm::event::KeyCode::Enter => {
                        match self.current_step {
                            FormStep::AccountType => {
                                self.next_step();
                            }
                            FormStep::AccountSubtype => {
                                if let Some(selected) = self.subtype_selection.selected() {
                                    if let Some(subtype) = self.subtypes.get(selected) {
                                        self.form_data.account_subtype = Some(subtype.clone());
                                        self.next_step();
                                    }
                                }
                            }FormStep::AccountName => {
                                self.next_step();
                            }FormStep::Confirmation => {
                                // Create the account data and return action
                                let account_data = CreateAccountData {
                                    code: self.form_data.code.clone(),
                                    name: self.form_data.name.clone(),
                                    account_type: self.form_data.account_type.clone().unwrap(),
                                    account_subtype: self.form_data.account_subtype.clone().unwrap(),
                                    currency: self.form_data.currency.clone(),
                                };
                                
                                self.hide();
                                return Ok(Some(Action::CreateAccount(account_data)));
                            }
                        }
                    }                    crossterm::event::KeyCode::Backspace => {
                        if matches!(self.current_step, FormStep::AccountName) {
                            self.input_buffer.pop();
                        }
                    }                    crossterm::event::KeyCode::Up => {
                        match self.current_step {
                            FormStep::AccountType => {
                                let selected = self.account_type_selection.selected().unwrap_or(0);
                                let new_selected = if selected == 0 {
                                    self.account_types.len().saturating_sub(1)
                                } else {
                                    selected - 1
                                };
                                self.account_type_selection.select(Some(new_selected));
                            }
                            FormStep::AccountSubtype => {
                                let selected = self.subtype_selection.selected().unwrap_or(0);
                                let new_selected = if selected == 0 {
                                    self.subtypes.len().saturating_sub(1)
                                } else {
                                    selected - 1
                                };
                                self.subtype_selection.select(Some(new_selected));
                            }
                            _ => {}
                        }
                    }
                    crossterm::event::KeyCode::Down => {
                        match self.current_step {
                            FormStep::AccountType => {
                                let selected = self.account_type_selection.selected().unwrap_or(0);
                                let new_selected = if selected >= self.account_types.len().saturating_sub(1) {
                                    0
                                } else {
                                    selected + 1
                                };
                                self.account_type_selection.select(Some(new_selected));
                            }
                            FormStep::AccountSubtype => {
                                let selected = self.subtype_selection.selected().unwrap_or(0);
                                let new_selected = if selected >= self.subtypes.len().saturating_sub(1) {
                                    0
                                } else {
                                    selected + 1
                                };
                                self.subtype_selection.select(Some(new_selected));
                            }
                            _ => {}
                        }
                    }                    crossterm::event::KeyCode::Char(c) => {
                        match self.current_step {
                            FormStep::AccountName => {
                                if c.is_alphanumeric() || c == ' ' || c == '-' || c == '_' {
                                    self.input_buffer.push(c);
                                }
                            }
                            _ => {}
                        }
                    }
                    crossterm::event::KeyCode::Left => {
                        if !matches!(self.current_step, FormStep::AccountType) {
                            self.previous_step();
                        }
                    }
                    _ => {}
                }
            }
        }

        Ok(None)
    }

    fn render(&self, frame: &mut Frame, area: Rect) -> Result<()> {
        if !self.is_visible {
            return Ok(());
        }

        // Create a centered popup
        let popup_area = centered_rect(80, 60, area);

        // Clear the area
        frame.render_widget(Clear, popup_area);

        // Main container
        let block = Block::default()
            .title("Create New Account")
            .borders(Borders::ALL)
            .border_style(Style::default().fg(Color::Blue));

        frame.render_widget(block, popup_area);

        // Inner area
        let inner = popup_area.inner(&ratatui::layout::Margin {
            horizontal: 1,
            vertical: 1,
        });

        // Split into sections
        let chunks = Layout::default()
            .direction(Direction::Vertical)
            .constraints([
                Constraint::Length(3), // Title/Step indicator
                Constraint::Min(8),    // Main content
                Constraint::Length(3), // Instructions
                Constraint::Length(2), // Error message
            ])
            .split(inner);        // Step indicator
        let step_text = format!(
            "Step {} of 4: {}",
            match self.current_step {
                FormStep::AccountType => 1,
                FormStep::AccountSubtype => 2,
                FormStep::AccountName => 3,
                FormStep::Confirmation => 4,
            },
            match self.current_step {
                FormStep::AccountType => "Select Account Type",
                FormStep::AccountSubtype => "Select Account Subtype",
                FormStep::AccountName => "Enter Account Name",
                FormStep::Confirmation => "Confirm Account Creation",
            }
        );
        let step_paragraph = Paragraph::new(step_text)
            .style(Style::default().fg(Color::Yellow))
            .wrap(Wrap { trim: true });
        frame.render_widget(step_paragraph, chunks[0]);        // Main content based on current step
        match self.current_step {
            FormStep::AccountType => {
                let items: Vec<ListItem> = self
                    .account_types
                    .iter()
                    .map(|account_type| {
                        ListItem::new(Self::get_account_type_display_name(account_type))
                    })
                    .collect();

                let list = List::new(items)
                    .block(Block::default().title("Select Account Type").borders(Borders::ALL))
                    .highlight_style(Style::default().bg(Color::Blue).fg(Color::White));

                frame.render_stateful_widget(list, chunks[1], &mut self.account_type_selection.clone());
            }
            FormStep::AccountSubtype => {
                let items: Vec<ListItem> = self
                    .subtypes
                    .iter()
                    .map(|subtype| {
                        ListItem::new(Self::get_subtype_display_name(subtype))
                    })
                    .collect();

                let list = List::new(items)
                    .block(Block::default().title("Select Subtype").borders(Borders::ALL))
                    .highlight_style(Style::default().bg(Color::Blue).fg(Color::White));

                frame.render_stateful_widget(list, chunks[1], &mut self.subtype_selection.clone());
            }            FormStep::AccountName => {
                let content = vec![
                    Line::from("Enter a name for the account:"),
                    Line::from(""),
                    Line::from(Span::styled(
                        format!("> {}", self.input_buffer),
                        Style::default().fg(Color::Green),
                    )),
                ];
                let paragraph = Paragraph::new(content).wrap(Wrap { trim: true });
                frame.render_widget(paragraph, chunks[1]);
            }
            FormStep::Confirmation => {
                let content = vec![
                    Line::from("Review account details:"),
                    Line::from(""),
                    Line::from(format!("Type: {:?}", self.form_data.account_type.as_ref().unwrap())),
                    Line::from(format!("Subtype: {:?}", self.form_data.account_subtype.as_ref().unwrap())),
                    Line::from(format!("Name: {}", self.form_data.name)),
                    Line::from(format!("Code: {}", self.form_data.code)),
                    Line::from(format!("Currency: {}", self.form_data.currency)),
                    Line::from(""),
                    Line::from(Span::styled(
                        "Press Enter to create account, Esc to cancel",
                        Style::default().fg(Color::Yellow),
                    )),
                ];
                let paragraph = Paragraph::new(content).wrap(Wrap { trim: true });
                frame.render_widget(paragraph, chunks[1]);
            }
        }        // Instructions
        let instructions = match self.current_step {
            FormStep::AccountType => "↑↓: Navigate • Enter: Select • Esc: Cancel",
            FormStep::AccountSubtype => "↑↓: Navigate • Enter: Select • ←: Back • Esc: Cancel",
            FormStep::AccountName => "Type to enter text • Enter: Next • ←: Back • Esc: Cancel",
            FormStep::Confirmation => "Enter: Create Account • ←: Back • Esc: Cancel",
        };
        let instructions_paragraph = Paragraph::new(instructions)
            .style(Style::default().fg(Color::DarkGray))
            .wrap(Wrap { trim: true });
        frame.render_widget(instructions_paragraph, chunks[2]);

        // Error message
        if let Some(error) = &self.error_message {
            let error_paragraph = Paragraph::new(error.as_str())
                .style(Style::default().fg(Color::Red))
                .wrap(Wrap { trim: true });
            frame.render_widget(error_paragraph, chunks[3]);
        }

        Ok(())
    }
}

/// Helper function to create a centered rectangle
fn centered_rect(percent_x: u16, percent_y: u16, r: Rect) -> Rect {
    let popup_layout = Layout::default()
        .direction(Direction::Vertical)
        .constraints([
            Constraint::Percentage((100 - percent_y) / 2),
            Constraint::Percentage(percent_y),
            Constraint::Percentage((100 - percent_y) / 2),
        ])
        .split(r);

    Layout::default()
        .direction(Direction::Horizontal)
        .constraints([
            Constraint::Percentage((100 - percent_x) / 2),
            Constraint::Percentage(percent_x),
            Constraint::Percentage((100 - percent_x) / 2),
        ])
        .split(popup_layout[1])[1]
}
